import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import LandingLayout from "../layouts/LandingLayout";
import { trpc } from "../utils/trpc";
import { signIn } from "next-auth/react";
import { Tabs } from "@mantine/core";
import { Disclosure } from "@headlessui/react";
import { HiChevronUp } from "react-icons/hi";
import { FAQs } from "../utils/content";
import { Button } from "@mantine/core";

const Home: NextPage = () => {
  const [activeTab, setActiveTab] = React.useState("STRIPE");
  return (
    <LandingLayout>
      <Head>
        <title>Stream Tools</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto flex flex-col items-center p-4 my-24">
        <h1 className="text-center text-5xl md:text-[5rem] font-extrabold  mb-6">
          Free yourself from the live stream grind
        </h1>
        <p className="text-2xl  text-center max-w-xl">
          Our tools help content creators and live streamers monetize their
          content and earn a living doing what they love.
        </p>
        <div className="flex flex-col md:flex-row gap-4 mt-6 w-full items-center justify-center">
          {/* <div
            onClick={() => signIn()}
            className="flex justify-center items-center cursor-pointer w-full md:w-fit px-4 py-3 rounded-lg border-2 border-gray-900 hover:bg-gray-100"
          >
            Get Started
          </div> */}
          <Button
            onClick={() => signIn()}
            color="brand.4"
            variant="outline"
            size="lg"
          >
            Get Started
          </Button>
          {/* <div className="flex justify-center items-center cursor-pointer w-full md:w-fit px-4 py-3 rounded-lg text-neutral-200 border-2 border-gray-900 bg-gray-900 hover:bg-gray-800">
            Learn More
          </div> */}
          <Button color="brand.4" size="lg">
            Learn More
          </Button>
        </div>
      </div>
      {/* <div className="w-full p-12 bg-slate-200 flex flex-col items-center">
        <h2 className="text-3xl md:text-4xl font-bold text-center mb-4">
          Helping Streamers Succeed
        </h2>
        <p className="max-w-xl text-center">
          Our suite of tools were built with creators in mind, and help you earn
          more for your time and effort.
        </p>
      </div> */}
      <div
        className="container mx-auto p-8 mt-12 flex flex-col items-center"
        id="how-it-works"
      >
        <h2 className="text-center text-3xl md:text-4xl font-bold">
          How It Works
        </h2>
        <p className="mt-4 text-center  w-full md:w-2/3">
          You're just 3 short steps away from earning more with your own
          personal donation link that you can share on your stream, social, or
          anywhere your audience can find it .
        </p>
        <div className="flex flex-col md:flex-row my-20">
          <div className="w-full md:w-1/3 p-6">
            <img className="mb-12 h-40" src={"/undraw_my_app_re_gxtj.svg"} />
            <p className="text-2xl font-semibold">1. Create an Account</p>
            <p className="mt-4">
              It's free to sign up and get started, just sign in with your
              Twitch, Youtube, or Discord account.
            </p>
          </div>
          <div className="w-full md:w-1/3 p-6">
            <img
              className="mb-12 h-40"
              src={"/undraw_stripe_payments_re_chlm.svg"}
            />
            <p className="text-2xl font-semibold">2. Connect with Stripe</p>
            <p className="mt-4">
              We use Stripe to handle all payments, and it's easy to get
              started, just connect your account with us.
            </p>
          </div>
          <div className="w-full md:w-1/3 p-6">
            <img
              className="mb-12 h-40"
              src={"/undraw_social_share_re_qb4v.svg"}
            />
            <p className="text-2xl font-semibold">3. Share your link</p>
            <p className="mt-4">
              Create a personalized link to share on your stream, or share on
              your socials and earn on your terms!
            </p>
          </div>
        </div>
      </div>
      <div className="my-20" id="faq">
        <h2 className="text-center text-3xl md:text-4xl font-bold">
          Frequently Asked Questions
        </h2>
        <div className="max-w-4xl mx-auto flex flex-col gap-2">
          <div className="w-full px-4 pt-16">
            <div className="mx-auto w-full">
              {FAQs.map((faq) => (
                <Disclosure>
                  {({ open }) => (
                    <>
                      <Disclosure.Button className="flex items-center w-full justify-between rounded-lg px-4 py-4 text-left text-sm font-medium bg-[#1A1A1B] hover:bg-[#333F44] mb-2">
                        <span className="text-xl font-semibold">
                          {faq.title}
                        </span>
                        <HiChevronUp
                          className={`${
                            open ? "rotate-180 transform" : ""
                          } h-5 w-5 duration-150`}
                        />
                      </Disclosure.Button>
                      <Disclosure.Panel className="px-4 pt-4 pb-2 text-sm text-gray-500">
                        {faq.body}
                      </Disclosure.Panel>
                    </>
                  )}
                </Disclosure>
              ))}
            </div>
          </div>
        </div>
      </div>
    </LandingLayout>
  );
};

export default Home;
